version: '3'
services:
  gitlab:
    build:
      context: .
      dockerfile: Dockerfile-gitlab
    environment:
      GITLAB_ROOT_PASSWORD: password
    ports:
      - '8000:80'
      - '2224:22'

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-workspace-volume:/var/jenkins_home/workspace
    environment:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-""}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-""}
        AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-""}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-""}

  verdaccio:
    build:
      context: .
      dockerfile: Dockerfile-verdaccio
    ports:
      - '4873:4873'

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
      - '8081:8081'


volumes:
  jenkins-workspace-volume: